// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWSJqSfUN-J_zZeraAcc_ERAQAi2w74ts',
    appId: '1:561801348644:web:52b85667606c0e52043ab1',
    messagingSenderId: '561801348644',
    projectId: 'chatapp-c612b',
    authDomain: 'chatapp-c612b.firebaseapp.com',
    storageBucket: 'chatapp-c612b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrSygMdoy6gcbiSu54YH-JliyYy2-_QU',
    appId: '1:561801348644:android:4e4dbdc2b6d7afc7043ab1',
    messagingSenderId: '561801348644',
    projectId: 'chatapp-c612b',
    storageBucket: 'chatapp-c612b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8vyyxoNmhvEn6ILiE0ZUScxPAfsQcQ0',
    appId: '1:561801348644:ios:08dd8e133ff851a3043ab1',
    messagingSenderId: '561801348644',
    projectId: 'chatapp-c612b',
    storageBucket: 'chatapp-c612b.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
